name: Build dist branch

on: [push]

permissions:
  contents: write

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish on dist branch
        run: |
          mv .git dist && cd dist
          git checkout dist/${{ github.ref_name }} || git checkout --orphan dist/${{ github.ref_name }}
          git add .
          git commit -m "Builded ${{ github.ref_name }}"
          git push origin dist/${{ github.ref_name }}
