name: Build dist branch

on:
  push:
  pull_request:
  

permissions:
  contents: write

env:
  BASE_URL: /CHANGE_ME_BASE_URL/

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish on dist branch
        if: github.event_name != 'pull_request'
        run: |
          mv .git dist && cd dist
          git checkout --orphan dist/${{ github.ref_name }}
          git add .
          git commit -m "Builded ${{ github.ref_name }}"
          git push origin dist/${{ github.ref_name }} -f
